# Site settings
title: Redemption
email: info@redemptionbc.org
description: It’s all about Jesus. Redemption is Bible-based church led by Pastor Ryan Huguley in Arlington Heights, Illinois.
baseurl: ""
url: "http://redemptionbc.github.io"
twitter_username: redemptionbc
github_username: redemptionbc

# Build settings
markdown: kramdown
